### ISSUE TITLE
Multi-line attributes

### ISSUE THREAD

**Issue by xxSkyy** [RyanScottLewis/haml-plain-loader#1]
Hi
I really appreciate that module , it made my life much easier in vuejs templates. But there are one thing I'm missing. I mean multi line attributes, I can't make it work in any way.

**Comment by RyanScottLewis** [comment]
Do you have an example of what you mean? This module only calls `haml.render` so anything that works in HAML should work with this.

**Comment by xxSkyy** [comment]
Sure , In my Ruby On Rails projects I use haml instead of erb files.
There I can define properties in hash with multi line support
```
%strong{:class => "code",
        :id => 'message fa'}
        Text
```

And it works very well

But in Vue in single file components code like this
```
<template lang="haml">
%strong{:class => "code",
        :id => 'message fa'}
        Text
</template>
```
causes errors in webpacker compiling cause of break between :class and :id property
so ATM for Vue im using html code cause many properties are unreadable in one line way
